/* sentences.js — 英语打砖块：每个单词配一句美式口语例句（单一数据源）
   格式约定（gen_sentence_mp3.py 依赖）：
   - 键用单引号 'word'，值用双引号 "…"；
   - 句内可含撇号（don't 等），但【不要】出现双引号或反斜杠；
   - 新增/修改例句后：改完本文件，重跑 gen_sentence_mp3.py 同步生成 audio/s/<word>.mp3。 */
var WORD_SENTENCES = {
  /* ---------- 动物 Animals ---------- */
  'cat': {en:"My cat is super cute. I love her so much.", zh:"我的猫超可爱，我超爱她。"},
  'dog': {en:"Let's take the dog for a walk.", zh:"我们带狗去散步吧。"},
  'fish': {en:"There are three fish in the tank.", zh:"鱼缸里有三条鱼。"},
  'bird': {en:"The bird sings every morning.", zh:"小鸟每天早上唱歌。"},
  'bear': {en:"Look, a big brown bear!", zh:"看，一只大棕熊！"},
  'frog': {en:"The frog jumps into the pond.", zh:"青蛙跳进池塘里。"},
  'duck': {en:"The duck can swim and quack.", zh:"鸭子会游泳还会嘎嘎叫。"},
  'cow': {en:"The cow gives us fresh milk.", zh:"奶牛给我们新鲜的牛奶。"},
  'pig': {en:"This pig is really cute and pink.", zh:"这头猪粉粉的，超可爱。"},
  'hen': {en:"The hen lays an egg every day.", zh:"母鸡每天下一个蛋。"},
  'rat': {en:"A rat ran across the street.", zh:"一只老鼠跑过了马路。"},
  'ant': {en:"The ant is carrying a big crumb.", zh:"蚂蚁搬着一大块面包屑。"},
  'bee': {en:"The bee is busy making honey.", zh:"蜜蜂忙着酿蜂蜜。"},
  'fox': {en:"The fox has a fluffy tail.", zh:"狐狸有一条毛茸茸的尾巴。"},
  'owl': {en:"The owl stays awake at night.", zh:"猫头鹰晚上不睡觉。"},
  'ape': {en:"The ape can climb trees fast.", zh:"猩猩爬树爬得很快。"},
  'bat': {en:"A bat flies in the dark sky.", zh:"蝙蝠在夜空中飞翔。"},
  'lion': {en:"The lion is the king of the jungle.", zh:"狮子是丛林之王。"},
  'wolf': {en:"The wolf howls at the moon.", zh:"狼对着月亮嚎叫。"},
  'deer': {en:"A deer is eating grass over there.", zh:"那边有只鹿在吃草。"},
  'shark': {en:"Don't worry, that shark is far away.", zh:"别担心，那条鲨鱼离得远。"},
  'whale': {en:"The whale is the biggest animal in the sea.", zh:"鲸鱼是海里最大的动物。"},
  'snake': {en:"The snake slides quietly on the ground.", zh:"蛇在地上悄悄爬行。"},
  'horse': {en:"She rides a horse every weekend.", zh:"她每个周末都骑马。"},
  'sheep': {en:"The sheep are eating grass on the hill.", zh:"绵羊在小山上吃草。"},
  'goat': {en:"The goat likes to climb on rocks.", zh:"山羊喜欢爬岩石。"},
  'mouse': {en:"The mouse is nibbling on some cheese.", zh:"老鼠在啃奶酪。"},
  'rabbit': {en:"My rabbit has long white ears.", zh:"我的兔子有一对长长的白耳朵。"},
  'tiger': {en:"The tiger has black stripes.", zh:"老虎身上有黑色条纹。"},
  'panda': {en:"The panda loves to eat bamboo.", zh:"熊猫爱吃竹子。"},

  /* ---------- 食物 Food ---------- */
  'apple': {en:"I eat an apple every morning.", zh:"我每天早上吃一个苹果。"},
  'bread': {en:"I want some bread and jam.", zh:"我想要点面包和果酱。"},
  'milk': {en:"Drink your milk, it makes you strong.", zh:"喝掉你的牛奶，能让你更强壮。"},
  'egg': {en:"I like my egg sunny-side up.", zh:"我喜欢单面煎的鸡蛋。"},
  'rice': {en:"We eat rice almost every day.", zh:"我们几乎每天吃米饭。"},
  'meat': {en:"This meat tastes really good.", zh:"这肉真好吃。"},
  'soup': {en:"The soup is hot, be careful.", zh:"汤很烫，小心点。"},
  'cake': {en:"Let's make a cake for your birthday.", zh:"我们给你做个生日蛋糕吧。"},
  'juice': {en:"Can I have some apple juice?", zh:"我能来点苹果汁吗？"},
  'water': {en:"Drink lots of water when it's hot.", zh:"天热的时候要多喝水。"},
  'grape': {en:"This grape is sweet and juicy.", zh:"这颗葡萄又甜又多汁。"},
  'peach': {en:"The peach smells so good.", zh:"这桃子闻起来真香。"},
  'lemon': {en:"This lemon is too sour for me.", zh:"这个柠檬对我来说太酸了。"},
  'cherry': {en:"I love cherry pie.", zh:"我爱吃樱桃派。"},
  'mango': {en:"The mango is sweet and soft.", zh:"这芒果又甜又软。"},
  'cream': {en:"Put some cream on your cake.", zh:"在蛋糕上放点奶油吧。"},
  'sugar': {en:"Too much sugar is bad for your teeth.", zh:"吃太多糖对牙齿不好。"},
  'honey': {en:"Bees make honey from flowers.", zh:"蜜蜂用花酿蜂蜜。"},
  'toast': {en:"I eat toast and eggs for breakfast.", zh:"我早餐吃吐司和鸡蛋。"},
  'cheese': {en:"Can you pass me the cheese?", zh:"把奶酪递给我好吗？"},
  'pizza': {en:"We ordered a big pizza for dinner.", zh:"我们晚餐点了一个大披萨。"},
  'noodle': {en:"I'm cooking noodles for you.", zh:"我在给你煮面条。"},
  'candy': {en:"Don't eat too much candy, okay?", zh:"别吃太多糖果，好吗？"},
  'cookie': {en:"These cookies are fresh and yummy.", zh:"这些饼干新鲜又好吃。"},
  'salad': {en:"I put some dressing on my salad.", zh:"我在沙拉上倒了点酱。"},
  'coffee': {en:"Dad drinks coffee every morning.", zh:"爸爸每天早上喝咖啡。"},
  'banana': {en:"This banana is yellow and ripe.", zh:"这根香蕉黄黄的，熟了。"},
  'orange': {en:"Peel the orange, then share it.", zh:"把橙子剥开，然后分着吃。"},
  'tomato': {en:"I put a tomato in my salad.", zh:"我在沙拉里放了一个西红柿。"},

  /* ---------- 身体 Body ---------- */
  'eye': {en:"Close your eyes and make a wish.", zh:"闭上眼睛许个愿。"},
  'ear': {en:"My ears get cold in winter.", zh:"冬天我的耳朵会冷。"},
  'arm': {en:"Raise your arm if you know the answer.", zh:"知道答案就举起手来。"},
  'leg': {en:"My leg hurts from all that running.", zh:"跑太多了，我的腿好疼。"},
  'lip': {en:"Put some lip balm on your lips.", zh:"在嘴唇上涂点润唇膏吧。"},
  'nose': {en:"My nose is running because of the cold.", zh:"感冒了，我一直在流鼻涕。"},
  'hand': {en:"Wash your hands before you eat.", zh:"吃东西前要洗手。"},
  'foot': {en:"I hurt my foot playing soccer.", zh:"我踢足球伤到了脚。"},
  'head': {en:"Wear a helmet to protect your head.", zh:"戴上头盔保护头部。"},
  'back': {en:"My back is a little sore today.", zh:"我今天背有点酸。"},
  'neck': {en:"Turn your neck slowly, don't rush.", zh:"慢慢转头，别着急。"},
  'knee': {en:"I fell and scraped my knee.", zh:"我摔了一跤，擦破了膝盖。"},
  'chin': {en:"He rested his chin on his hands.", zh:"他用手托着下巴。"},
  'heel': {en:"My heel hurts in these new shoes.", zh:"穿这双新鞋我的脚跟疼。"},
  'skin': {en:"Use sunscreen to protect your skin.", zh:"涂防晒霜保护皮肤。"},
  'tooth': {en:"Brush your teeth twice a day.", zh:"每天刷两次牙。"},
  'elbow': {en:"Don't put your elbows on the table.", zh:"别把手肘放在桌子上。"},
  'thumb': {en:"My thumb is sticky from the candy.", zh:"吃了糖果，我的大拇指黏黏的。"},
  'wrist': {en:"I wear a watch on my wrist.", zh:"我手腕上戴着一块表。"},
  'ankle': {en:"She twisted her ankle on the stairs.", zh:"她在楼梯上扭伤了脚踝。"},
  'brain': {en:"Reading is good for your brain.", zh:"阅读对大脑有好处。"},
  'heart': {en:"My heart beats fast when I run.", zh:"我跑步时心跳得很快。"},
  'blood': {en:"The doctor took a little blood.", zh:"医生抽了一点血。"},
  'bone': {en:"Milk makes your bones strong.", zh:"牛奶能让你的骨头更强壮。"},
  'mouth': {en:"Open your mouth wide and say ahh.", zh:"张大嘴巴，说啊。"},
  'finger': {en:"I have a small cut on my finger.", zh:"我手指上有个小伤口。"},
  'tongue': {en:"Hold your tongue, that's rude.", zh:"别乱说话，这样不礼貌。"},
  'chest': {en:"Put your hand on your chest and breathe.", zh:"把手放在胸口，深呼吸。"},
  'waist': {en:"The belt is too tight around my waist.", zh:"腰带系在腰上太紧了。"},
  'shoulder': {en:"He gave me a pat on the shoulder.", zh:"他拍了拍我的肩膀。"},

  /* ---------- 自然 Nature ---------- */
  'sun': {en:"The sun is so bright today.", zh:"今天太阳好刺眼。"},
  'moon': {en:"The moon looks big and round tonight.", zh:"今晚月亮又大又圆。"},
  'star': {en:"Look at all the stars in the sky!", zh:"看天上那么多星星！"},
  'sky': {en:"The sky is clear and blue today.", zh:"今天天空湛蓝晴朗。"},
  'sea': {en:"We can see the sea from the window.", zh:"从窗户能看到大海。"},
  'tree': {en:"The birds are singing in the tree.", zh:"小鸟在树上唱歌。"},
  'rock': {en:"Don't throw rocks at the window.", zh:"别往窗户扔石头。"},
  'sand': {en:"My shoes are full of sand.", zh:"我的鞋里全是沙子。"},
  'wave': {en:"The big wave knocked me down.", zh:"大浪把我打倒了。"},
  'wind': {en:"The wind is blowing hard today.", zh:"今天风刮得很大。"},
  'fire': {en:"Stay away from the fire, it's dangerous.", zh:"离火远点，很危险。"},
  'lake': {en:"Let's go fishing at the lake.", zh:"我们去湖边钓鱼吧。"},
  'hill': {en:"We rolled down the small hill.", zh:"我们从那个小山坡上滚下来。"},
  'rain': {en:"Bring an umbrella, it might rain.", zh:"带把伞，可能会下雨。"},
  'snow': {en:"It snowed all night long.", zh:"雪下了一整夜。"},
  'cloud': {en:"The cloud looks like a white sheep.", zh:"那朵云看起来像只白羊。"},
  'river': {en:"The river runs through the town.", zh:"河流穿过小镇。"},
  'ocean': {en:"I love swimming in the ocean.", zh:"我喜欢在海里游泳。"},
  'beach': {en:"Let's build a castle on the beach.", zh:"我们在沙滩上堆城堡吧。"},
  'storm': {en:"The storm is coming, close the windows.", zh:"暴风雨要来了，关好窗户。"},
  'field': {en:"The cows are in the field.", zh:"奶牛都在田野里。"},
  'plant': {en:"Water the plant every few days.", zh:"每隔几天给植物浇一次水。"},
  'earth': {en:"The earth goes around the sun.", zh:"地球绕着太阳转。"},
  'stone': {en:"He skipped a stone across the lake.", zh:"他打了个水漂。"},
  'grass': {en:"The grass is soft under my feet.", zh:"脚下的草软软的。"},
  'leaf': {en:"The leaf turned orange in fall.", zh:"秋天叶子变黄了。"},
  'flower': {en:"She picked a pretty flower for me.", zh:"她为我摘了一朵漂亮的花。"},
  'mountain': {en:"We hiked up the mountain all morning.", zh:"我们爬了一上午山。"},
  'island': {en:"The island is tiny and quiet.", zh:"这座小岛又小又安静。"},
  'forest': {en:"The forest is full of tall trees.", zh:"森林里长满了大树。"},

  /* ---------- 颜色与形状 Colors & Shapes ---------- */
  'red': {en:"My favorite color is red.", zh:"我最喜欢的颜色是红色。"},
  'blue': {en:"The blue car is mine.", zh:"那辆蓝色的车是我的。"},
  'gold': {en:"She won a gold medal.", zh:"她赢得了一枚金牌。"},
  'pink': {en:"Her dress is bright pink.", zh:"她的裙子是亮粉色。"},
  'gray': {en:"The sky turned gray before the rain.", zh:"下雨前天变灰了。"},
  'black': {en:"I like my black backpack.", zh:"我喜欢我的黑色背包。"},
  'white': {en:"The snow is soft and white.", zh:"雪又软又白。"},
  'green': {en:"The grass is green after the rain.", zh:"雨后草变绿了。"},
  'brown': {en:"He has brown eyes and hair.", zh:"他有着棕色的眼睛和头发。"},
  'purple': {en:"The purple flower smells sweet.", zh:"紫色的花闻起来很香。"},
  'circle': {en:"Draw a big circle on the paper.", zh:"在纸上画一个大圆圈。"},
  'square': {en:"The window is a square shape.", zh:"那扇窗户是正方形的。"},
  'triangle': {en:"A slice of pizza is a triangle.", zh:"一片披萨是三角形的。"},
  'diamond': {en:"The diamond ring sparkles a lot.", zh:"钻石戒指闪闪发光。"},
  'oval': {en:"The egg is an oval shape.", zh:"鸡蛋是椭圆形的。"},
  'cross': {en:"Don't cross the street when it's red.", zh:"红灯时不要过马路。"},

  /* ---------- 动作 Actions ---------- */
  'run': {en:"Let's run to the park, it's not far.", zh:"我们跑到公园吧，不远。"},
  'jump': {en:"Can you jump as high as me?", zh:"你能跳得和我一样高吗？"},
  'swim': {en:"I swim in the pool every summer.", zh:"每年夏天我都在游泳池游泳。"},
  'fly': {en:"We will fly to Beijing tomorrow.", zh:"我们明天飞往北京。"},
  'eat': {en:"Let's eat lunch together.", zh:"我们一起吃午饭吧。"},
  'read': {en:"I read a book before bed.", zh:"我睡前会读一本书。"},
  'sing': {en:"She sings very well, I love it.", zh:"她唱得真好，我好喜欢。"},
  'dance': {en:"Let's dance to this song!", zh:"我们跟着这首歌跳舞吧！"},
  'draw': {en:"I draw pictures of my family.", zh:"我会画我的家人。"},
  'play': {en:"Let's play hide and seek.", zh:"我们玩捉迷藏吧。"},
  'clap': {en:"Everybody clap your hands!", zh:"大家拍拍手！"},
  'kick': {en:"He can kick the ball really far.", zh:"他能把球踢得很远。"},
  'pull': {en:"Pull the door, don't push it.", zh:"拉门，别推。"},
  'push': {en:"Push the swing for me, please.", zh:"请帮我推秋千。"},
  'lift': {en:"Can you lift this heavy box?", zh:"你能举起这个重箱子吗？"},
  'drop': {en:"Be careful, don't drop your phone.", zh:"小心点，别把手机摔了。"},
  'catch': {en:"Try to catch the ball!", zh:"试着接住球！"},
  'throw': {en:"Throw the ball to me.", zh:"把球扔给我。"},
  'climb': {en:"He likes to climb the tree.", zh:"他喜欢爬树。"},
  'smile': {en:"Say cheese and smile for the photo.", zh:"拍照啦，笑一笑。"},
  'laugh': {en:"That joke made everyone laugh.", zh:"那个笑话逗得大家哈哈大笑。"},
  'shout': {en:"Don't shout, we can hear you.", zh:"别喊，我们能听到。"},
  'write': {en:"Write your name at the top.", zh:"在最上面写上你的名字。"},
  'paint': {en:"We paint with watercolors in class.", zh:"我们上课用水彩画画。"},
  'build': {en:"Let's build a sand castle.", zh:"我们堆个沙堡吧。"},
  'cook': {en:"Dad will cook dinner tonight.", zh:"今晚爸爸做饭。"},
  'wash': {en:"Wash your face after you wake up.", zh:"起床后要洗脸。"},
  'sleep': {en:"I sleep eight hours every night.", zh:"我每晚睡八个小时。"},
  'stand': {en:"Stand in a line, please.", zh:"请排好队站好。"},

  /* ---------- 学校 School ---------- */
  'book': {en:"This book is awesome, you should read it.", zh:"这本书超棒，你应该读一读。"},
  'pen': {en:"Can I borrow your blue pen?", zh:"我能借下你的蓝笔吗？"},
  'desk': {en:"My desk is full of books.", zh:"我的书桌堆满了书。"},
  'ruler': {en:"Use the ruler to draw a straight line.", zh:"用尺子画直线。"},
  'paper': {en:"Fold the paper into a paper plane.", zh:"把纸折成纸飞机。"},
  'pencil': {en:"Sharpen your pencil before class.", zh:"上课前把铅笔削好。"},
  'eraser': {en:"I need an eraser to fix this.", zh:"我需要橡皮擦改一下这里。"},
  'school': {en:"I go to school by bus.", zh:"我坐公交车上学。"},
  'teacher': {en:"Our teacher is really nice and funny.", zh:"我们老师人很好还很搞笑。"},
  'student': {en:"Every student gets a new book.", zh:"每个学生都有一本新书。"},
  'class': {en:"Class starts at eight o'clock.", zh:"八点开始上课。"},
  'lesson': {en:"Today's lesson is about animals.", zh:"今天的课是关于动物的。"},
  'homework': {en:"Do your homework before you play.", zh:"做完作业再玩。"},
  'exam': {en:"Don't stress, the exam is easy.", zh:"别紧张，考试很简单的。"},
  'bag': {en:"Put your books in your bag.", zh:"把书放进书包里。"},
  'map': {en:"Let's look at the map to find the park.", zh:"我们看看地图找公园吧。"},
  'clock': {en:"The clock says it's time to go.", zh:"钟表显示该走了。"},
  'chair': {en:"Pull up a chair and sit down.", zh:"拉把椅子坐下吧。"},
  'board': {en:"Write the answer on the board.", zh:"把答案写在黑板上。"},
  'glue': {en:"Put some glue on the paper.", zh:"在纸上涂点胶水。"},
  'crayon': {en:"Color it with your red crayon.", zh:"用你的红色蜡笔涂色。"},
  'library': {en:"The library is quiet, shh.", zh:"图书馆很安静，嘘。"},
  'playground': {en:"We play on the playground at noon.", zh:"中午我们在操场上玩。"},
  'bell': {en:"The bell rings, class is over.", zh:"铃响了，下课了。"},
  'math': {en:"I'm good at math and science.", zh:"我擅长数学和科学。"},
  'english': {en:"Let's practice English every day.", zh:"我们每天练习英语吧。"},
  'music': {en:"She is learning to read music.", zh:"她正在学看乐谱。"},

  /* ---------- 日用品 Daily Items ---------- */
  'cup': {en:"This cup is full of hot tea.", zh:"这杯子里装满了热茶。"},
  'plate': {en:"Pass me a clean plate, please.", zh:"请递我一个干净的盘子。"},
  'bowl': {en:"My bowl is full of soup.", zh:"我的碗里盛满了汤。"},
  'knife': {en:"Be careful with the knife.", zh:"小心用刀。"},
  'spoon': {en:"Use a spoon to eat the soup.", zh:"用勺子喝汤。"},
  'table': {en:"Dinner is ready on the table.", zh:"晚饭准备好了，在桌上。"},
  'door': {en:"Don't forget to lock the door.", zh:"别忘了锁门。"},
  'window': {en:"Open the window, it's hot.", zh:"打开窗户吧，好热。"},
  'lamp': {en:"Turn on the lamp, it's getting dark.", zh:"天黑了，打开台灯吧。"},
  'bed': {en:"Time to go to bed, good night.", zh:"该睡觉了，晚安。"},
  'sofa': {en:"The cat is sleeping on the sofa.", zh:"猫在沙发上睡觉。"},
  'phone': {en:"My phone is ringing, hang on.", zh:"我电话响了，等一下。"},
  'brush': {en:"Use the brush to clean your shoes.", zh:"用刷子刷干净你的鞋。"},
  'towel': {en:"Dry your hands with a towel.", zh:"用毛巾把手擦干。"},
  'soap': {en:"Wash your hands with soap.", zh:"用肥皂洗手。"},
  'comb': {en:"Use a comb to fix your hair.", zh:"用梳子梳下头发。"},
  'mirror': {en:"Look in the mirror, your hair is messy.", zh:"照照镜子，你头发乱糟糟的。"},
  'basket': {en:"Put the apples in the basket.", zh:"把苹果放进篮子里。"},
  'candle': {en:"Blow out the candles and make a wish.", zh:"吹灭蜡烛，许个愿。"},
  'pillow': {en:"My pillow is soft and comfy.", zh:"我的枕头又软又舒服。"},
  'blanket': {en:"Wrap yourself in a warm blanket.", zh:"把自己裹进温暖的毯子里。"},
  'bucket': {en:"Fill the bucket with water.", zh:"把水桶装满水。"},
  'bottle': {en:"Take a water bottle with you.", zh:"带个水瓶去吧。"},
  'key': {en:"I can't find my key anywhere.", zh:"我到处找不到我的钥匙。"},
  'umbrella': {en:"Take your umbrella, it looks rainy.", zh:"带上伞吧，看起来要下雨了。"},
  'camera': {en:"Smile, the camera is on you.", zh:"笑一笑，相机对着你呢。"},
  'ladder': {en:"Be careful climbing up the ladder.", zh:"爬梯子要小心。"},
  'rope': {en:"Hold the rope tight, don't let go.", zh:"抓紧绳子，别松手。"}
};
